### PR TITLE
Ui for posts for #12

### PR DESCRIPTION
**Pull request by rohan2734**
image

### CODE REVIEW

**Review by ExpressHermes — CHANGES_REQUESTED** [review]
1. Instead of having two seperate buttons for showing the number of likes/comments and liking/commenting on the post, can you merge them into single one. 

2. The padding of image on horizontal axis is too much. Decrease it. 

3. There are merge conflicts. Resolve them.

**Comment by rohan2734** [comment]
>Instead of having two seperate buttons for showing the number of likes/comments and liking/commenting on the post, can you merge them into single one.

actually there was only one button,but like this it is very good looking , as you can see the options for like,share and comment are looking now neat, and for their count we are displaying seperately , even that is looking neat, but if we merge them, it is not looking good.

>The padding of image on horizontal axis is too much. Decrease it.

actually i tried doing that, but it was not, but i will give one more try,

**Comment by rohan2734** [comment]
@mann27  @ExpressHermes  ,if you like the UI, please give me a good or extra points.

**Comment by mann27** [comment]
Resolved merge conflicts.

**Review by mann27 — APPROVED** [review]

**Comment by mann27** [comment]
give @rohan2734 25 points

**Comment by rohan2734** [comment]
> give @rohan2734 25 points

can i get a few more points, because i didn't know grid and material core styling , and i had to learn them and do , thats why ,it took time for doing that.

**Pull request merged**
