### PR TITLE
'home-UI'

### PR DESCRIPTION
**Pull request by Tushardeepak**

### CODE REVIEW

**Review by ExpressHermes — COMMENTED** [review]
Attach a screenshot @Tushardeepak

**Comment by Tushardeepak** [comment]
Screenshot (480)

**Review by mann27 — APPROVED** [review]

**Comment by ExpressHermes** [comment]
@mann27 Award @Tushardeepak appropriate marks

**Comment by mann27** [comment]
give @Tushardeepak 75 points

**Pull request merged**
