### PR TITLE
Comment -UI ( Back )

### PR DESCRIPTION
**Pull request by Tushardeepak**
Screenshot (498)

### CODE REVIEW

**Review by ExpressHermes — COMMENTED** [review]
What is the purpose of `text.txt` file?

**Review by mann27 — APPROVED** [review]
UI looks good!
Try not to change the 'xyz' to "xyz" and adding the spaces. If this happens by an extension disable it. That makes it hard for us to review the real changes and decide the lines of code changes.

**Review by ExpressHermes — APPROVED** [review]

**Comment by Tushardeepak** [comment]
Sry for the Text.txt You can delete that file.

**Comment by ExpressHermes** [comment]
> Sry for the Text.txt You can delete that file.

Just delete this file and make a commit to the same PR

**Comment by ExpressHermes** [comment]
give @Tushardeepak 75 points

**Pull request merged**
