### PR TITLE
Validate add post on backend

### PR DESCRIPTION
**Pull request by rohan2734**
* I  have added some validation on backend for
* title,body,tags
* I didnt test it till now,I know how to do testing in postman,
* i tested the routes with mongodb,
* to test it , I want to know how previously you tested this route,
* like Bearer token in headers, and contentType:"applicaiton/json", and some data,
* When i am clear,I will test them and I will work on frontend of validating add post

### CODE REVIEW

**Review by ExpressHermes — COMMENTED** [review]
There are some conflicts. Can you see to that @rohan2734 ?

**Comment by ExpressHermes** [comment]
@rohan2734 Have you resolved conflicts on GitHub interface? I am asking so that if you haven't, I will help you resolve them

**Comment by rohan2734** [comment]
> @rohan2734 Have you resolved conflicts on GitHub interface? I am asking so that if you haven't, I will help you resolve them

ya these confilcts, were already resolved on my other pull req, but these confilcts are repeating again and again. there is no conflicts actually.

**Comment by ExpressHermes** [comment]
Resolve them once again and whenever you are making a PR make sure to pull the latest changes in the report using `git pull upstream`

**Comment by rohan2734** [comment]
> Resolve them once again and whenever you are making a PR make sure to pull the latest changes in the report using `git pull upstream`

ok i will try, you can merge the reusable post component, once it is done, i will go ```git pull upstream``` and automatically conflicts would be resolved

**Comment by mann27** [comment]
give @rohan2734 25 points

**Comment by rohan2734** [comment]
> Resolve them once again and whenever you are making a PR make sure to pull the latest changes in the report using `git pull upstream`

image


 i tried it , just now , it is saying i dont have access for that,  which command shall i use?

**Comment by ExpressHermes** [comment]
@rohan2734 I think you forgot to add `upstream` in your local repo. Add it using following command:
```
git add remote upstream https://github.com/mann27/News24x7-Client.git
```

**Comment by rohan2734** [comment]
> ```
> git add remote upstream https://github.com/mann27/News24x7-Client.git
> ```


image
still the same problem.
I have deleted my rohan2734/newsclinet repo ,as it was not updating, and cloned it again, and tried this, 
but same problem exists.

**Comment by rohan2734** [comment]
> git add remote upstream https://github.com/mann27/News24x7-Client.git

i think it is

```
git remote add upstream....
```

**Pull request merged**
